provider:
  name: faas
  gateway: http://localhost:8080
  network: func_functions

functions:
  tweetstargazer:
    lang: python
    handler: ./tweet-stargazer
    image: alexellis2/tweet-stargazer
    environment_file:
     - twitter_secrets.yml

  tweetfanclub:
    lang: python
    handler: ./tweet-fanclub
    image: alexellis2/tweet-fanclub

  tweetpolaroid:
    skip_build: true
    image: alexellis2/faas-polaroid:0.1

